<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>979a43a8-46e3-4cf2-a683-6e003e883b8d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingSoftwareWithLLMs.Application\BuildingSoftwareWithLLMs.Application.csproj" />
    <ProjectReference Include="..\BuildingSoftwareWithLLMs.Infrastructure\BuildingSoftwareWithLLMs.Infrastructure.csproj" />
  </ItemGroup>

</Project>
